import { initFooterAccordions } from "./modules/footer-accordions.js";
import { initForms } from "./modules/forms.js";
import { initArticleFilter } from "./modules/article-filter.js";
import { initMobileMenu } from "./modules/mobile-menu.js";
import { initModelCatalog } from "./modules/model-catalog.js";
import { initPartSearch } from "./modules/part-search.js";
import { initReviewsToggle } from "./modules/reviews-toggle.js";
import { initScrollPagination } from "./modules/scroll-pagination.js";
import { initSliders } from "./modules/sliders.js";
import { initCareerDialog } from "./modules/career-dialog.js";
import { initVacancyDetailDialog } from "./modules/vacancy-detail-dialog.js";

initMobileMenu();
initArticleFilter();
initModelCatalog();
initPartSearch();
initReviewsToggle();
initFooterAccordions();
initForms();
initScrollPagination();
initSliders();
initVacancyDetailDialog();
initCareerDialog();
