import { readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Script } from "node:vm";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entryFile = resolve(projectRoot, "js/main.js");
const vendorFile = resolve(projectRoot, "vendor/swiper/swiper-bundle.min.js");
const outputFile = resolve(projectRoot, "app.js");
const modules = new Map();

const importPattern = /import\s+\{([^}]+)\}\s+from\s+["']([^"']+)["'];?/gu;
const namedExportPattern = /export\s+\{([^}]+)\};?/gu;
const declarationExportPattern = /export\s+(?=(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*))/gu;

const parseModule = async (file) => {
  if (modules.has(file)) return modules.get(file);

  const source = await readFile(file, "utf8");
  const imports = [...source.matchAll(importPattern)].map((match) => ({
    names: match[1].split(",").map((name) => name.trim()).filter(Boolean),
    file: resolve(dirname(file), match[2]),
  }));
  const exports = new Set();

  for (const match of source.matchAll(namedExportPattern)) {
    match[1].split(",").map((name) => name.trim()).filter(Boolean).forEach((name) => exports.add(name));
  }
  for (const match of source.matchAll(declarationExportPattern)) exports.add(match[1]);

  const module = { file, imports, exports: [...exports], source };
  modules.set(file, module);
  await Promise.all(imports.map(({ file: dependency }) => parseModule(dependency)));
  return module;
};

await parseModule(entryFile);

const orderedModules = [];
const visited = new Set();
const visit = (file) => {
  if (visited.has(file)) return;
  visited.add(file);
  const module = modules.get(file);
  module.imports.forEach(({ file: dependency }) => visit(dependency));
  orderedModules.push(module);
};
visit(entryFile);

const moduleNames = new Map(orderedModules.map(({ file }, index) => [file, `__module${index}`]));
const renderModule = (module) => {
  const imports = module.imports
    .map(({ names, file }) => `  const { ${names.join(", ")} } = ${moduleNames.get(file)};`)
    .join("\n");
  const body = module.source
    .replace(importPattern, "")
    .replace(namedExportPattern, "")
    .replace(declarationExportPattern, "")
    .trim();
  const exported = module.exports.length
    ? `\n  return Object.freeze({ ${module.exports.join(", ")} });`
    : "";
  const label = relative(projectRoot, module.file);

  return [
    `  // source: ${label}`,
    `  const ${moduleNames.get(module.file)} = (() => {`,
    imports,
    body.split("\n").map((line) => line ? `  ${line}` : "").join("\n"),
    exported,
    "  })();",
  ].filter(Boolean).join("\n");
};

const vendor = (await readFile(vendorFile, "utf8"))
  .replace(/\n?\/\/# sourceMappingURL=.*$/u, "")
  .trim();
const banner = [
  "/* AutoMD JavaScript bundle.",
  " * Generated by `npm run build`; edit js/main.js or js/modules/*.js.",
  " */",
].join("\n");
const output = `${banner}\n(() => {\n  \"use strict\";\n\n${vendor}\n\n  window.Swiper = Swiper;\n\n${orderedModules.map(renderModule).join("\n\n")}\n})();\n`;

new Script(output, { filename: "app.js" });
await writeFile(outputFile, output, "utf8");
console.log(`Built app.js from Swiper and ${orderedModules.length} first-party modules.`);
